version: '3'

services:
  web:
    build:
      context: .
      target: nginx_server
    ports:
      - '80:80'
  api:
    build:
      context: .
      target: node_server
    ports:
      - '5656:5656'