language: node_js
node_js:
  - "10"
dist: trusty
cache:
  directories:
    - node_modules
install: 
  - npm install --legacy-peer-deps
  - npm run prod-build
script: 
  - npm run test
  - python3 -VV
  - pip install --upgrade pip
  - pip -V
env:
  global:  PATH=/opt/python/3.7.1/bin:$PATH
